# Gaussian environment configuration
name: gaussian
n_arms: 10
seed: 42
environment:
  gaussian:
    name: gaussian
    n_arms: 10
    seed: 42
    easy_range: [0.1, 0.3]
    hard_range: [0.7, 0.9]
    std: 0.1  # Standard deviation for all arms 